### ISSUE TITLE
Cannot find module 'loadash'

### ISSUE THREAD

**Issue by telmotrooper** [Ethaan/nodejs-tibia-api#1]
I'm trying to use **tibia-api** in my [Express](https://expressjs.com/) application using "require" instead of "import", since that's what Express projects do by default.

The problem is that as soon as I do `let tibia = require("tibia-api");` I get the following error:
```
`module.js:538
    throw err;
    ^

Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/telmo/bosque-em-ferobra/node_modules/tibia-api/lib/utils.js:8:15)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```

I tried installing lodash with `npm install --save lodash` and adding `let lodash = require("lodash");` to my code, but it still doesn't work. Isn't there a way to use your module with "require"? Thank you.

**Comment by Ethaan** [comment]
@telmotrooper good point, let me fix it so it also works with EcmaScript5 or lower
